### ISSUE TITLE
connot making new env

### ISSUE THREAD

**Issue by SHYang1210** [vikashplus/mj_envs#5]

**Comment by SHYang1210** [comment]
[2019-09-11 11:14:52,042] Making new env: hammer-v0
Traceback (most recent call last):
  File "visualize_env.py", line 45, in <module>
    main()
  File "/home/s/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/s/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/s/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "visualize_env.py", line 26, in main
    env = gym.make(env_name)
  File "/home/s/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/s/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/s/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/s/mj_envs/mj_envs/hand_manipulation_suite/hammer_v0.py", line 16, in __init__
    mujoco_env.MujocoEnv.__init__(self, curr_dir+'/assets/DAPG_hammer.xml', 5)
  File "/home/s/mj_envs/mj_envs/mujoco_env.py", line 30, in __init__
    self.model = load_model_from_path(fullpath)
  File "mujoco_py/cymj.pyx", line 131, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: /home/s/mj_envs/mj_envs/hand_manipulation_suite/assets/DAPG_hammer.xml. mj_loadXML error: b"Error: could not open STL file '/home/s/mj_envs/mj_envs/hand_manipulation_suite/assets/../../../dependencies/Adroit/resources/meshes/forearm_simple.stl'\nObject name = forearm_simple, id = 0, line = 58, column = 9"
